### ISSUE TITLE
运行action报错

### ISSUE THREAD

**Issue by BILY5354** [eryajf/awesome-stars-eryajf#2]
你好，我按流程配置好后，在action中执行失败，错误提示如下，请问是哪一个步骤出现了问题？谢谢。
![image](https://user-images.githubusercontent.com/46767838/182351030-fb65fb98-70c9-402b-b069-a3aafd1b8e02.png)

**Comment by eryajf** [comment]
配置信息是否与我的完全一致呢，感觉上版本的问题



| |
eryajf
|
|
***@***.***
行者常至，为者常成！
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年08月02日 18:15 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [eryajf/awesome-stars-eryajf] 运行action报错 (Issue #2) |

你好，我按流程配置好后，在action中执行失败，错误提示如下，请问是哪一个步骤出现了问题？谢谢。

**Comment by eryajf** [comment]
uses: simonecorsi/mawesome@v2

把版本换成这个试试

**Comment by BILY5354** [comment]
刚复制你成功运行的yml，现在我也可以看到了。谢谢
![image](https://user-images.githubusercontent.com/46767838/182360929-1c121ba8-226a-4864-b4ee-c41291bf3206.png)
